# Generated by Django 4.2.4 on 2023-08-06 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_userprofile_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='fullname',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='phoneno',
            new_name='phone_no',
        ),
    ]
